"""Agregar restriccion inscripciones

Revision ID: 322d6f86c4f0
Revises: d31ecdd2a830
Create Date: 2026-03-09 20:52:43.969270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322d6f86c4f0'
down_revision = 'd31ecdd2a830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_alumno_curso', ['alumno_id', 'curso_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_alumno_curso', type_='unique')

    # ### end Alembic commands ###
